services:
  - type: web
    name: bookclub
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn bookclub.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: bookclub.settings
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: bookclub-db
    databaseName: bookclub
    user: bookclub_user
    postgresMajorVersion: 15